name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(git rev-parse --short $GITHUB_SHA)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker Image
        run: docker build -t ci_cd_studies_image:${{ steps.generate_tag.outputs.sha }} .
